version: '3'
services:
  jenkins:
    build: .
    image: tjozsa/mobile-jenkins:latest
    ports:
      - '8080:8080'
      - '50000:50000'
      - '52382:52382'
    volumes:
      - './jenkins_home:/var/jenkins_home'